# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "10955dd9a7859fcc61e6d5c98aec4b04"
name = "restrocustomerui"
application_url = "https://seats-allows-soviet-exactly.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "retrospecdevelopmentstore.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_payment_customizations,write_payment_customizations,write_products"

[auth]
redirect_urls = [
  "https://seats-allows-soviet-exactly.trycloudflare.com/auth/callback",
  "https://seats-allows-soviet-exactly.trycloudflare.com/auth/shopify/callback",
  "https://seats-allows-soviet-exactly.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
